[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "oriongeno"
version = "1.0.2"
authors = [{ name = "OrionGeno Group", email = "zhangchao5@genomic.cn" }]
description = "OrionGeno is an end-to-end model for ab initio eukaryotic gene annotation from genome FASTA to GTF."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10,<3.11"
dependencies = [
    'numpy>=1.26.4',
    'biopython>=1.85',
    'einops>=0.8.1',
    'typing_extensions>=4.15',
    'torch>=2.7.0',
    'transformers>=4.57,<5',
    'tokenizers>=0.22,<0.23',
    'huggingface_hub>=0.34',
    'safetensors>=0.5',
    'mamba-ssm>=2.2.5',
    'causal-conv1d>=1.5.2',
    'triton>=3.3',
]

[project.scripts]
oriongeno = "oriongeno.cli:main"

[project.urls]
"Homepage" = "https://github.com/BGIResearch/OrionGeno"
"Repository" = "https://github.com/BGIResearch/OrionGeno.git"
"Bug Tracker" = "https://github.com/BGIResearch/OrionGeno/issues"
"Changelog" = "https://github.com/BGIResearch/OrionGeno/releases"

[tool.setuptools.packages.find]
where = ["."]
include = ["oriongeno*"]
exclude = ["tests*", "test*", "output*", "outputs*", "checkpoints*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"oriongeno.model_packages" = ["species_embeddings_pca_formatted_numpy_float32.pkl"]
