"""Shared OrionGeno runtime constants."""

SEQUENCE_GROUP_SIZE = 10240000
DEFAULT_MAX_FASTA_RECORDS = 0
DEFAULT_FRAGMENTED_RECORD_THRESHOLD = 1
DEFAULT_PACK_SPACER_LEN = 0
DEFAULT_PACK_TARGET_SIZE = 20000000
DEFAULT_PARALLEL_FACTOR = 100
DEFAULT_MAX_CHUNKS_PER_INFERENCE_GROUP = 256
