"""Shared OrionGeno runtime constants."""

SEQUENCE_GROUP_SIZE = 51200000
DEFAULT_SEQUENCE_LENGTH = 640000
DEFAULT_FLANK_SIZE = 40000
DEFAULT_BATCH_SIZE = "auto"
DEFAULT_HMM_DECODE_BATCH = "auto"
DEFAULT_MAX_FASTA_RECORDS = 0
DEFAULT_GENE_FILTER_MODE = "strict"
DEFAULT_FRAGMENTED_RECORD_THRESHOLD = 1
DEFAULT_PACK_SPACER_LEN = 4096
DEFAULT_PACK_TARGET_SIZE = 51200000
DEFAULT_PARALLEL_FACTOR = 100
DEFAULT_MAX_CHUNKS_PER_INFERENCE_GROUP = 256
